apiVersion: v1
kind: Service
metadata:
  name: user-form-service
spec:
  selector:
    app: user-form
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
